language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install -U pytest-cov
  - pip install -U codecov
  
install:
  - pip install -r minimum_requirements.txt
  - python setup.py install
# command to run tests
script:
  - export TEST_DATA_DIR=${TRAVIS_BUILD_DIR}/data/test/;
  - export NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1;
  - pytest --cov=svrimg tests/
  
after_success:
  - codecov