language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
before_install:
  - python setup.py install
install:
  - pip install -r minimum_requirements.txt
# command to run tests
script:
  - pytest
