language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
before_install:
  - python setup.py install
install:
  - pip install -r minimum_requirements.txt
# command to run tests
script:
  - export TEST_DATA_DIR=${TRAVIS_BUILD_DIR}/data/test/;
  - export NUMPY_EXPERIMENTAL_ARRAY_FUNCTION=1;
  - pytest
  
after_success:
  - codecov